version: '3.8'

services:
  # Nginx - take all incoming requests and trigger PHP interpreter
  server: 
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:etc/nginx/nginx.conf:ro
  # Running and executing PHP and  Laravel Code
  php:
  # Holds the sql database
  mysql:
  composer:
  artisan:
  npm:
